### ISSUE TITLE
Wrong extract example 

### ISSUE THREAD

**Issue by Germey** [Gerapy/GerapyAutoExtractor#2]
* http://www.rtfund.com/main/gyrt/xxpl/index.shtml
* http://www.hr-fund.com.cn/news/information_2.html

Some title were not extracted successfully.

只提取出了一部分，有一些标题没有提取出来。

**Comment by lanZzV** [comment]
https://www.dfa66.com/dfaets/news/infodisclosure/announcement/index.html
https://www.hsqhfunds.com/front/left_100186.jhtml

the same problem

**Comment by Germey** [comment]
Fixed.
