### ISSUE TITLE
How to distinguish whether the page is a list page or a detail page?

### ISSUE THREAD

**Issue by shuguang101** [Gerapy/GerapyAutoExtractor#3]

**Comment by Germey** [comment]
I'll implement this algorithm later. 

Please keep this issue open~

**Comment by Germey** [comment]
New version released, please try the latest version:

```
pip3 install -U gerapy-auto-extractor
```

Pls see [README](https://github.com/Gerapy/GerapyAutoExtractor/blob/master/README.md) for the usage instruction.
